Device: cuda
Dataset: cityscapes, Train set: 2975, Val set: 500
[!] Retrain
Epoch 1, Itrs 10/30000, Loss=1.565319
Epoch 1, Itrs 20/30000, Loss=0.749803
Epoch 1, Itrs 30/30000, Loss=0.955776
Epoch 1, Itrs 40/30000, Loss=0.819565
Epoch 1, Itrs 50/30000, Loss=0.630952
Epoch 1, Itrs 60/30000, Loss=0.741756
Epoch 1, Itrs 70/30000, Loss=0.721029
Epoch 1, Itrs 80/30000, Loss=0.712828
Epoch 1, Itrs 90/30000, Loss=0.600439
0it [00:00, ?it/s]/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torchvision/transforms/functional.py:423: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torchvision/transforms/functional.py:423: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
Epoch 1, Itrs 100/30000, Loss=0.681174
Model saved as checkpoints/test_CityScapesV2_2022-09-09_155240/latest_deeplabv3plus_resnet101_cityscapes_os16.pth
validation...




























95it [01:00,  1.57it/s]
Traceback (most recent call last):
  File "/home/chenht/.conda/envs/epe/lib/python3.8/multiprocessing/queues.py", line 245, in _feed
    send_bytes(obj)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/chenht/.conda/envs/epe/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/PIL/ImageFile.py", line 495, in _save
    fh = fp.fileno()
AttributeError: '_idat' object has no attribute 'fileno'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "main.py", line 503, in <module>
    main()
  File "main.py", line 473, in main
    val_score, ret_samples = validate(
  File "main.py", line 283, in validate
    plt.savefig(f'results/{opts.run_name}/val_samples/{img_id}_overlay_iter{iter}.png', bbox_inches='tight', pad_inches=0)
  File "/home/chenht/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 979, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/chenht/.local/lib/python3.8/site-packages/matplotlib/figure.py", line 3046, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/chenht/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/home/chenht/.local/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/home/chenht/.local/lib/python3.8/site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/home/chenht/.local/lib/python3.8/site-packages/matplotlib/backends/backend_agg.py", line 541, in print_png
    mpl.image.imsave(
  File "/home/chenht/.local/lib/python3.8/site-packages/matplotlib/image.py", line 1675, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/PIL/Image.py", line 2212, in save
    save_handler(self, fp, filename)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 1348, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/PIL/ImageFile.py", line 509, in _save
    l, s, d = e.encode(bufsize)
KeyboardInterrupt