Device: cuda
Boost set: <datasets.carla.Carla object at 0x7f8631981550>Dataset: nightlab, Train set: 2998, Val set: 1299
[!] Retrain
Traceback (most recent call last):
  File "main.py", line 567, in <module>
    main()
  File "main.py", line 515, in main
    loss.backward()
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/chenht/.conda/envs/epe/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.